@startuml Get All Hotels (GET)




header Sample VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Get All Hotels (GET)"




participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<controllers>>\n:hotels" as controllersHotels
participant "<<model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelsDatabase




client->server ++:req.get('/hotels')
server->routerHotels ++:app.use('/hotels',hotels)
routerHotels -> controllersHotels ++:getHotels()
controllersHotels->modelHotel ++:get(hotels)




modelHotel ->HotelsDatabase ++: HotelSchema
HotelsDatabase --> modelHotel --: hotel
controllersHotels <-- modelHotel --:hotel
controllersHotels->client --:response




@enduml
